--MEMORY
CREATE TABLE MEMORY 
(
  TIMESTAMP DATE NOT NULL 
, SGA NUMBER NOT NULL 
, PGA NUMBER NOT NULL 
, CONSTRAINT MEMORY_PK PRIMARY KEY 
  (
    TIMESTAMP 
  )
);


--CPU
CREATE TABLE CPU 
(
  TIMESTAMP DATE NOT NULL 
, NUM_CPU_CORES NUMBER NOT NULL 
, IOWAIT_TIME NUMBER NOT NULL 
, NICE_TIME NUMBER NOT NULL 
, BUSY_TIME NUMBER NOT NULL 
, USER_TIME NUMBER NOT NULL 
, NUM_CPUS NUMBER NOT NULL 
, IDDLE_TIME NUMBER NOT NULL 
, CONSTRAINT CPU_PK PRIMARY KEY 
  (
    TIMESTAMP 
  )
  ENABLE 
);


--Datafiles
CREATE TABLE DATAFILES 
(
  FILENAME VARCHAR2(256) NOT NULL 
, SIZE_FILE NUMBER NOT NULL 
, USED NUMBER NOT NULL 
, PCT_USED NUMBER NOT NULL 
, CONSTRAINT DATAFILES_PK PRIMARY KEY 
  (
    FILENAME 
  )
  ENABLE 
);


--Sessions
CREATE TABLE SESSIONS 
(
  SID NUMBER NOT NULL 
, TIMESTAMP DATE NOT NULL 
, BOX VARCHAR2(256) NOT NULL 
, OS_USER VARCHAR2(256) NOT NULL 
, PROGRAM VARCHAR2(256) NOT NULL 
, CONSTRAINT SESSIONS_PK PRIMARY KEY 
  (
    SID
  , OS_USER
  )
  ENABLE 
);


--Grants
CREATE TABLE GRANTS 
(
  GRANTEE VARCHAR2(256) NOT NULL 
, PRIVILEGE VARCHAR2(256) NOT NULL 
, ADMIN_OPTION INT NOT NULL 
, COMMON INT NOT NULL 
, INHERITED INT NOT NULL 
, COLUMN1 DATE NOT NULL 
, CONSTRAINT GRANTS_PK PRIMARY KEY 
  (
    GRANTEE 
  , PRIVILEGE 
  )
  ENABLE 
);


--Users
CREATE TABLE USERS 
(
  USERNAME VARCHAR2(256) NOT NULL 
, DEFAULT_TABLESPACE VARCHAR2(256) NOT NULL 
, TEMPORARY_TABLESPACE VARCHAR2(256) NOT NULL 
, LAST_LOGIN DATE 
, SESSION_USERNAME VARCHAR2(256) NOT NULL 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USERNAME 
  )
  ENABLE 
);


--Tablespaces
CREATE TABLE TABLESPACES 
(
  TABLESPACE VARCHAR2(256) NOT NULL 
, PCT_USED NUMBER NOT NULL 
, TOTAL_MB NUMBER NOT NULL 
, USED_MB NUMBER NOT NULL 
, FREE_MB NUMBER NOT NULL 
, DATAFILES NUMBER NOT NULL 
, USERNAME VARCHAR(256) NOT NULL
, DATAFILE_NAME VARCHAR2(256) 
, CONSTRAINT TABLESPACES_PK PRIMARY KEY 
  (
    TABLESPACE 
  )
  ENABLE 
);

ALTER TABLE TABLESPACES
ADD CONSTRAINT TABLESPACES_FK1 FOREIGN KEY
(
  DATAFILE_NAME 
)
REFERENCES DATAFILES
(
  FILENAME 
)
ENABLE;

ALTER TABLE TABLESPACES
ADD CONSTRAINT TABLESPACES_FK2 FOREIGN KEY
(
    USERNAME
)
REFERENCES USERS
(
    USERNAME
)
ENABLE;



--Tables
CREATE TABLE TABLES 
(
  TIMESTAMP DATE NOT NULL 
, SCHEMA VARCHAR2(256) NOT NULL 
, OBJECT VARCHAR2(256) NOT NULL 
, OBJECT_SIZE NUMBER NOT NULL 
, TABLESPACE VARCHAR2(256) 
, CONSTRAINT TABLES_PK PRIMARY KEY 
  (
    TIMESTAMP 
  , SCHEMA 
  , OBJECT 
  )
  ENABLE 
);

ALTER TABLE TABLES
ADD CONSTRAINT TABLES_FK1 FOREIGN KEY
(
  TABLESPACE
)
REFERENCES TABLESPACES
(
  TABLESPACE
)
ENABLE;